### ISSUE TITLE
Add view for admins to see which hosts are inactive

### ISSUE THREAD

**Issue by pim0223** [CollActionteam/clothing-loop#101]
## What
Some hosts become inactive, and they no longer welcome new members to their loop. This can be bad, because it gives people the idea that the whole app is inactive.

## How to fix
Create a view that shows users that have signed up, but are not activated by the host yet (`active` field on user has to be present for this to work)

**Comment by lil5** [comment]
moved to trello https://trello.com/c/MeoY6uyP
