### ISSUE TITLE
Header redesign

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#113]
This page should follow the design requirements as showing in [this design file](https://www.figma.com/file/IyRXwabKQqCUEqBPCd4Zlh/The-Clothing-Loop---web-app-design).
The main functionalities are:
- Logo should have a link on click that directs the user to the homepage
- visible button tab for 'start a new loop'
- tab for 'login'
- language switcher

**Comment by tberm** [comment]
Done in #124
