### ISSUE TITLE
Login page redesign

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#116]
This page should follow the design requirements as showing in [this design file](https://www.figma.com/file/IyRXwabKQqCUEqBPCd4Zlh/The-Clothing-Loop---web-app-design?node-id=0%3A1).
 The main functionalities are:
- once the email is submitted, the user should receive a verification email which allows to log in
- page restyling following the design guidelines
- add header and footer

**Comment by pariksh1th** [comment]
Can I work on this issue.
