### ISSUE TITLE
Signup flow redesign

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#117]
This page should follow the design requirements as showing in [this design file](https://www.figma.com/file/IyRXwabKQqCUEqBPCd4Zlh/The-Clothing-Loop---web-app-design?node-id=0%3A1).
The main functionalities are:
- form fields should be consistent (geocoding map field to capture should be replaced - this is something to implement further)
- user fills up the form and on submit, triggers a confirmation email 
- page restyling following the design guidelines
- add header and footer

**Comment by pariksh1th** [comment]
Hey , I am interested in this .
