### ISSUE TITLE
Start new Loop flow redesign

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#118]
This page should follow the design requirements as showing in [this design file](https://www.figma.com/file/IyRXwabKQqCUEqBPCd4Zlh/The-Clothing-Loop---web-app-design?node-id=0%3A1).
The main functionalities are:
- signup form 
- select loop location 
- add loop information (description, categories, sizes)
- on submit, trigger a confirmation email 
- the flow should have a progression bar

**Comment by tberm** [comment]
I've started having a look at this. Let me know if anyone else would like to as I'm sure some help will be useful!
