### ISSUE TITLE
Map visualization: add clustering

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#133]
Implement loops visualization in the map:

- loops should be displayed as blurred circles
- loops centre point should  be set by the coordinates of the loop location stored in db 
- loops radius value should be the one set by the user in NewChainLocation.tsx flow (this is still in building process, can be hardcoded for now)
- loops should have different colours based on their category 
- when zooming out the map, cluster nearby loops into a single circle and display the loops count 

![image](https://user-images.githubusercontent.com/52887737/148544231-c8b9a0c5-1fe0-4c93-8974-f7d8901793af.png)

**Comment by emer7** [comment]
Note for reference (and self): I just realized that since this is a clustering problem I might consider using clustering algorithm i.e. Machine Learning algorithm. I am eyeing at DBSCAN algorithm.

**Comment by giuliamml** [comment]
Mapbox has built-in map clustering functions - https://docs.mapbox.com/mapbox-gl-js/example/cluster/ 
What do you think of this?

**Comment by emer7** [comment]
Thanks Giulia, I don't know MapBox has clustering under their hood already. Looks good and it will definitely be more performant than self-implemented.

But the issue is that we will need to have GeoJSON format for our coordinates. Shouldn't be a big issue but I'll update if there is major issue
