### ISSUE TITLE
Clean up/refactor Firebase frontend import, initialization, etc.

### ISSUE THREAD

**Issue by emer7** [CollActionteam/clothing-loop#134]
Firebase is currently imported/initialized/etc. in many places in the code, which causes inconsistency of Firebase's internal data/state/config and also contributes to many repeated redundant code.

Said repeated redundant code e.g.
```
if (process.env.REACT_APP_USE_EMULATOR == 'true') {
  functions.useEmulator('localhost', 5001);
}
```

**Comment by lil5** [comment]
Firebase has been replaced with a GoLang server on a cheap VPS
