### ISSUE TITLE
Donation functionality

### ISSUE THREAD

**Issue by JBijker** [CollActionteam/clothing-loop#137]
Work in progress: front-end almost finished, back-end in progress

**Comment by JBijker** [comment]
See branch https://github.com/CollActionteam/clothing-loop/tree/%23137-donation-functionality

**Comment by JBijker** [comment]
OK, I think it's finished.

## Front-end
Two new Components were added: `DonationForm` the form and processing logic, and `Donate.tsx`, a wrapper for the form. I've now added a route on /donation to the donate page.

## Back-end
One new Callable Function: `paymentInitiate`, this is called when submitting the donation form, after communicating with the Stripe API on the front-end.
One new HTTP Function: `paymentWebhook`, this is called directly by Stripe, after processing a payment.
Both functions are in `payments.src`.

## What's needed to go live

1. A new Stripe account should be set up, either on CollAction or on the new stichting.
2. For recurring payments, the amount options have to be chosen and set up in Stripe. The ID's for these amounts have to be updated in the front-end.
3. Currently there is no e-mail sent to the user that donated, this can be added to the Stripe Webhook logic.
4. There are two new parameters for Firebase Functions config: `stripeKey` and `stripeWebhookSecret`. The first is the test or live Stripe API Key, the second is the secret that's used to validate the signature of a Stripe Webhook call. Both can be found in Stripe's dashboard.

**Comment by giuliamml** [comment]
This is great, thank you!

We're looking into setting up a new Stripe account and will then update what's needed to go live. 
I'm also working on a section on the landing page to then link it to your donation flow.

Meanwhile, feel free to create PR when ready!

**Comment by emer7** [comment]
@JBijker Hi do you mind if you created a PR for the firebase functions so that we can merge the functions code? Right now the functions are already in the Firebase but not in the code and it causes the build pipeline to fail.

Alternatively I think we might need to delete your functions from the Firebase for the moment until you merge the whole branch.

Thank you!
