### ISSUE TITLE
Code styling standardization

### ISSUE THREAD

**Issue by emer7** [CollActionteam/clothing-loop#144]
With the expanding codebase, having a unified code styling that can be applied using Prettier for example will be useful for everyone.

We can discuss what the code styling that we can have here.

**Comment by giuliamml** [comment]
I agree, let's discuss this during the weekly call!

**Comment by emer7** [comment]
From the call just now, we'll have this as the code style/format
this is the default .prettierrc config, but will be useful for anyone that has custom config installed into their machine such that their formatting may obscure their PR
```
// .prettierrc
{
  "arrowParens": "always",
  "bracketSameLine": false,
  "bracketSpacing": true,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "useTabs": false
}
```
