### ISSUE TITLE
Styling standardization

### ISSUE THREAD

**Issue by emer7** [CollActionteam/clothing-loop#146]
Currently we have various styling approaches.

To catalogue our approaches so far:
1. style property in JSX element `i.e. <Element style={{...}} />`
2. Material UI with classes property
2. Material UI with theme.ts
3. App.css with className

So far the conclusion is to continue with whatever works for each contributors (i.e. no action is needed)

**Comment by lil5** [comment]
As the theme `const` is not the correct type and is forced back to `any` on every page it's used.

In an ideal codebase it would be separated between; MUI Theme configurations, global css and component specific css.

Relates to #89

**Comment by lil5** [comment]
[tailwind](https://tailwindcss.com/) + [daisyui](https://daisyui.com/) have replaced all css and the mui framework
