### ISSUE TITLE
Newsletter signup dialog on landing page

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#168]
In the landing page, create a popup 30seconds after the user is on the page. 
The popup should:
-  gets displayed only the first time a user is visiting the landing page 
- get a confirmation message once signed up
- replicate the newsletter design currently built in the footer

**Comment by giuliamml** [comment]
<img width="735" alt="Screenshot 2022-02-14 at 17 38 30" src="https://user-images.githubusercontent.com/52887737/153916985-e0dc3914-97b7-4f2e-a270-c23a6d363c60.png">

**Comment by lil5** [comment]
This is a user hostile addition.
