### ISSUE TITLE
Automated email custom domain setup

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#171]
Currently, the sender of all automated emails is a random email address (clothingloop7@gmail.com), replace it with the custom domain hello@clothingloop.org or noreply@clothingloop.org

**Comment by emer7** [comment]
![image](https://user-images.githubusercontent.com/21377166/152842983-e6a80bc4-e5e6-4418-b088-024351cc687c.png)

This is the sample email right?

**Comment by emer7** [comment]
Fixed the sender email address :)

![image](https://user-images.githubusercontent.com/21377166/155469133-25450775-ab0e-4d84-ad91-1dd8102d630b.png)
![image](https://user-images.githubusercontent.com/21377166/155469202-5b0d1b60-5ee9-4b4d-83a0-534e0f994c77.png)

**Comment by giuliamml** [comment]
> Fixed the sender email address :)
> 
> ![image](https://user-images.githubusercontent.com/21377166/155469133-25450775-ab0e-4d84-ad91-1dd8102d630b.png) ![image](https://user-images.githubusercontent.com/21377166/155469202-5b0d1b60-5ee9-4b4d-83a0-534e0f994c77.png)

Looking good! Thank you :)
