### ISSUE TITLE
Location detector  

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#172]
Dutch loops are slowly going to be migrated into the platform, meanwhile if a user based in The Netherlands wants to join will have to signup using a [google form](https://docs.google.com/forms/d/e/1FAIpQLSfeyclg6SjM3GRBbaBprFZhoha3Q9a7l3xs1s9eIDpKeVzi6w/viewform). 
Currently, this form is reachable when clicking on the static loop displayed in The Netherlands, however, it would be good to display a pop-up message to all Dutch users visiting the platform.
To do so, retrieve the user IP/browser location and if it matches a location in The Netherlands, display a pop-up.

Extra info:
- check privacy requirements for this feature as might need to request permission to access user's location 
- match the design:
<img width="810" alt="Screenshot 2022-02-07 at 15 26 30" src="https://user-images.githubusercontent.com/52887737/152818035-e1e78251-fe66-4263-b05a-4776de96649f.png">

**Comment by tberm** [comment]
To avoid having to get permission to a user's precise location I am planning on making a call to https://ip-api.com/ to find out whether the user's IP is from the Netherlands. This seems to be free to use with no API key as long as the use is non-commercial and there are no more than 45 requests per minute per IP, which seems fine for us.

While we could probably get away with making a call on every page load, I'm planning to store the result (i.e. `ipIsFromNetherlands = "true" | "false"`) in localStorage. So on every page load we will check localStorage first and then make an API call if needed. If the user appears to be in the Netherlands the popup will appear every time they load the /loops/find page.

@giuliamml @timstokman please let me know if either of you are against this approach.

**Comment by timstokman** [comment]
I'd personally advice against circumventing the browser's privacy features by using a third party like this. Sure, it's convenient, but also a little shady. 

You could trigger the popup when they click somewhere in the netherlands, or when they share their location through the browser.

**Comment by giuliamml** [comment]
I'd take Tim's advice and not use third-party solutions. 
And regarding the implementation of the feature, I think what you're suggesting works well
