### ISSUE TITLE
Signup emails update based on user type

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#185]
Currently, the confirmation email sent when a user starts a new loop and joins an existing loop, is the same. Would be good to have to differentiate the copy based on the recipient's user type.

**Comment by giuliamml** [comment]
### If the user type is a chainAdmin use the following copy:

> Hello, and welcome to the Clothing Loop! Thank you for making the step to create a more sustainable world together.
> 
> We are super happy to have you. Please find our manual in the attachment to see how to proceed.
> 
> Right now everything is set up, but the loop is not live. When you are ready, login and move the slider to ‘visible’. Don’t wait too long, as someone else may beat you to the chase and start a loop in the same area. And even though there can be multiple loops in the same area, it may cause a bit of confusion. 
> 
> The Clothing Loop team

**Comment by giuliamml** [comment]
### If the user type is null:

> Hello again!
> You are now officially registered to the Clothing Loop!
> 
> What happens next?
> Each Loop has a local host that coordinates the specific Loop voluntarily. He/she/they will receive your application, and get in touch with further info. Please be patient, sometimes this can take up to four weeks, depending on the available time of the host.
> 
> Of course, you want to start swapping right away, which we applaud obviously! What you can do in the meantime is start scanning your closet for items that are ready to go on adventures with somebody else. You can check if they need some repairs, depilling or a little wash, so they will become an even better addition to our travelling swap bags. Please note, it’s a mutual effort to keep the bag a surprise for everyone. This way we are not just passing on a bag of clothes but a bag of happy stories and care! Don’t worry if you do not find something in the very first bag
> 
> Furthermore, we love to grow as fast as possible to make the most impact. The sooner the better! So, another thing you can help us with is spread the word amongst your family, friends and neighbours. The earth will be eternally grateful.
> 
> Happy swapping!
> 
> The Clothing Loop team

**Comment by emer7** [comment]
Currently the email is sent on user signup which at the point user has not been assigned with any role (except Admin)
Then does that mean shall we shift the email sending to after loop is created?

**Comment by emer7** [comment]
Sorry for just noticing this. We shall we include the email verification link? Or this email will be sent separately from the email verification link (i.e. user will receive 2 emails)?

**Comment by giuliamml** [comment]
I think it should include the verification link, so we don't have to generate two separated emails. I'll need to ask to update the copies, as the ones above don't reference the verification link. I'll update you on this

**Comment by lil5** [comment]
Confirmation email has been replaced by a login verification email that it user type agnostic
