### ISSUE TITLE
Partial header shadow from search bar

### ISSUE THREAD

**Issue by tberm** [CollActionteam/clothing-loop#214]
The search bar contained in the header on the "find loops" page and home page has a drop shadow but the rest of the header does not, resulting in an odd-looking grey line that does not span the full width of the header

![image](https://user-images.githubusercontent.com/49910363/162790753-974a1cdc-87e8-411f-8fe4-d5413f32d5a1.png)

**Comment by lil5** [comment]
shadow has been removed
