### ISSUE TITLE
Browsers compatibility 

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#227]
Check browser compatibility on main browsers - Chrome, Mozilla and Safari

**Comment by giuliamml** [comment]
Suggested tool I've used before: https://www.browserstack.com/ but open to other suggestions.

**Comment by lil5** [comment]
Testing the website on 3 browsers running (Gecko, Chromium, Webkit) engines like (Firefox, Brave or Chrome, Gnome web or Safari) respectively, should be enough.

mui includes a css reset that should decrease changes between operating systems: [MUI Baseline](https://mui.com/material-ui/react-css-baseline/#global-reset)
