### ISSUE TITLE
Add chain limit option

### ISSUE THREAD

**Issue by navase** [CollActionteam/clothing-loop#25]
- Hosts should be able to add a chain limit (maximum amount of members) when creating a chain.
- Hosts should be able to edit the chain limit.
- We display chains that are full in grey on the map.
- On the card of a full chain, we add a message that the chain is full, but that you can start a new chain.

**Comment by pim0223** [comment]
Question is: do we want waiting lists? No waiting lists might simplify it a lot, the user either picks another chain or starts their own. I would be a fan of simplicity: no waiting list, but variable limits (decided by the host).

**Comment by navase** [comment]
Discussed with Nichon: we start without a waiting list. The host can change the chain limit if they want to open the chain for more members.
