### ISSUE TITLE
Add restriction that user can only join one chain

### ISSUE THREAD

**Issue by navase** [CollActionteam/clothing-loop#29]

**Comment by pim0223** [comment]
This should probably be implemented in the sign up form: it checks if the email is in our db, and if it is, it states: contact your admin.

Better even is that we allow a user to change a chain, v2 functionality.

**Comment by navase** [comment]
Discussed with Nichon: we don't know how many current users are in two chains, but we think there are some (e.g. chains for overlapping sizes, or two chains in the same city). Therefore, we don't want to add this restriction right now. After importing the existing users, we want to check how many users this would affect and make a decision then.
