### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#85]
The app has already been set up for internationalization with the package [i18n](https://www.npmjs.com/package/i18n), just need to check that all the pages across the app are actually getting translated

**Comment by lil5** [comment]
#243

**Comment by lil5** [comment]
The [Crowdin Project](https://crowdin.com/project/the-clothing-loop) needs to have an integration to this GitHub repository.
I assume @timstokman is the person to ask about this?

**Comment by lil5** [comment]
Moved here https://trello.com/c/THcexSr0
