### ISSUE TITLE
E-mail notifications for chain frontend

### ISSUE THREAD

**Issue by timstokman** [CollActionteam/clothing-loop#9]
Solves following requirements:
* Chain member: Gets an email with all information about how to start a chain.
* User: Gets a confirmation email when joining a chain.
* Host: Gets an email with all information about how to start a chain. Gets an email every time a new member applies for their chain.
* Users can unsubscribe from chains with email address: fill in email address, get an email with confirmation link, get removed when clicking said link.

**Comment by pim0223** [comment]
@timstokman can you give a description on what you mean by this?
